name: ⚡ XServer 自动续期

on:
  schedule:
    # 初始设定为 UTC 04:27 (即日本时间 13:27)，完美错峰，后续将由 Python 脚本动态接管篡改
    - cron: '27 4 23 7 *'
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          python -m pip install --upgrade pip
          pip install playwright requests playwright-stealth
          playwright install --with-deps chromium

      - name: Run Script
        env:
          XSERVER_EMAIL: ${{ secrets.XSERVER_EMAIL }}
          XSERVER_PASSWORD: ${{ secrets.XSERVER_PASSWORD }}
          YESCAPTCHA_KEY: ${{ secrets.YESCAPTCHA_KEY }}
          GEMINI_API_KEYS: ${{ secrets.GEMINI_API_KEYS }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          PROXY_IP: ${{ secrets.PROXY_IP }}
          PROXY_PORT: ${{ secrets.PROXY_PORT }}
          PROXY_USER: ${{ secrets.PROXY_USER }}
          PROXY_PASS: ${{ secrets.PROXY_PASS }}
          PAT_WITH_WORKFLOW_SCOPE: ${{ secrets.PAT_WITH_WORKFLOW_SCOPE }}
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python renew.py
